services:
  db:
    image: postgres:${POSTGRES_VERSION:-14.11}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-indexer}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-randompassword}
      POSTGRES_DB: ${POSTGRES_DB:-apptoss_LOCAL_indexer}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB_VM_PORT:-5432}:5432

volumes:
  db-data:
